########################################
##
##  Beroepen Config File
##
########################################

##error bericht dat je krijgt bij /beroep add [beroepnaam]
foute_argumenten_1: "Foutieve argument gebruik: /beroep add [beroepnaam]"

##error bericht dat je krijgt bij /beroep add [beroepnaam]
geen_speler_error: "Alleen spelers kunnen dit gebruiken !"