name: beroepen
main: me.jensie1996.jasper.MainClass
version: 2.1.0
commands:
    beroep:
        description: test
        usage: /<command
    info: 
        description: Geeft info weer over de Plugin
        usage: /<command>   
    update: 
        description: Kijk of er een update is ...
        usage: /<command>   