name: jasper
main: me.jensie1996.jasper.MainClass
version: 2.0.0
commands:
    beroep:
        description: test
        usage: /<command
    info: 
        description: Geeft info weer over de Plugin
        usage: /<command>   